### ISSUE TITLE
Quadratic use of #

### ISSUE THREAD

**Issue by crusso** [enzoh/mo-hex#1]
https://github.com/enzoh/mo-hex/blob/59055d49ffe931766fddd5a63af2df222c5dda21/src/hex.mo#L32

**Comment by enzoh** [comment]
What is the internal representation of `Text`? I'm not seeing much else available in the API.. https://github.com/dfinity-lab/motoko/blob/master/stdlib/text.mo

**Comment by enzoh** [comment]
Would be great to get something in that API like
```motoko
public concatMap<T>(xs : List<T>, f : T -> Text) : Text
```

**Comment by crusso** [comment]
Text is utf8, I believe.
I don't think we yet have the primitives to do something efficient here. I'd like something like:
`Array.toText<A>(a:[mut A], src: Nat; len:Nat) -> Text` 
so we can at least build something like a buffered `TextBuilder` class.

This issue wasn't meant a criticism of your code, I just wanted to give you a heads up about complexity.

Our internal `debug_show<T>` functions are also quadratic....

**Comment by rckprtr** [comment]
Hey guys, Im still learning Motoko and thought it would be interesting to look into this.  

https://gist.github.com/rckprtr/c5eee49a55dc3126d4f58667166ab306

At scale textBuilder performed better then textAppend, about 10x. 

The problem is toText(), how do you convert a char[] to Text ... I feel like Im missing something simple.

**Comment by crusso** [comment]
> Hey guys, Im still learning Motoko and thought it would be interesting to look into this.
> https://gist.github.com/rckprtr/c5eee49a55dc3126d4f58667166ab306
> At scale textBuilder performed better then textAppend.
> The problem is toText(), how do you convert a char[] to Text ... I feel like Im missing something simple.

Hi Rick, 
Thanks for looking into this!

You are indeed missing something simple but we need to explicitly provide it as a language built-in. You currently cannot code it yourself, unfortunately. 
That's exactly what I was getting at above with the function 
```
Array.toText(a : [var Char], src : Nat, len : Nat) -> Text
```
The idea is that it would construct a text from a slice of a mutable array, e.g. in your code it would be `toText(values,0,count)`.

**Comment by nomeata** [comment]
The latest version of Motoko uses a different internal string representation where you can use `#` without this quadratic behaviour, so I guess this can be closed.
